name: Update wiki
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://iotmod:${{secrets.GITHUB_TOKEN}}@github.com/iotmod/hornet-wiki.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "https://iotmod:${{secrets.GITHUB_TOKEN}}@github.com/iotmod/hornet-wiki.wiki.git"
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
