name: Update wiki
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pull remote
      run: |
        git remote add upstream https://github.com/iotmod/hornet-wiki.wiki.git
        git fetch upstream
        git push upstream master
